function(disable_external_warnings target)
    if (MSVC)
        target_compile_options(${target} PRIVATE "/W0")
    else ()
        target_compile_options(${target} PRIVATE "-w")
    endif ()
endfunction ()
