include(CMakeFindDependencyMacro)

find_dependency(fmt REQUIRED)
find_dependency(freetype REQUIRED)
find_dependency(glad REQUIRED)
find_dependency(glfw3 REQUIRED)
find_dependency(glm CONFIG REQUIRED)
find_dependency(unofficial-minizip REQUIRED)
find_dependency(nlohmann_json REQUIRED)
find_dependency(nlohmann_json_schema_validator REQUIRED)
find_dependency(OpenGL REQUIRED)
find_dependency(PNG REQUIRED)
find_dependency(scn CONFIG REQUIRED)
find_dependency(Stb REQUIRED)
find_dependency(Threads REQUIRED)
find_dependency(tinyxml2 REQUIRED)
find_dependency(Tracy REQUIRED)
find_dependency(ZLIB REQUIRED)

if (NOT TARGET sgct_stb)
  add_library(sgct_stb INTERFACE IMPORTED GLOBAL)
  add_library(sgct::stb ALIAS sgct_stb)
  target_include_directories(sgct_stb INTERFACE ${Stb_INCLUDE_DIR})
endif ()

include("${CMAKE_CURRENT_LIST_DIR}/sgctTargets.cmake")
